version: '3.8'

services:
  tw_stocker_crawler:
    image: nk7260ynpa/tw_stocker_crawler:latest
    container_name: tw_stocker_crawler
    ports:
      - "6738:6738"
    restart: "always"
    networks:
        - db_network
  
  tw_stocker_daily_process:
    image: nk7260ynpa/tw_stocker_daily_process:latest
    container_name: tw_stocker_daily_process
    restart: "always"
    networks:
        - db_network

networks:
  db_network:
    external: true