services:
  database:
      image: mysql:8.3
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports: 
          - 3306:3306
      environment: 
          MYSQL_USER: user 
          MYSQL_PASSWORD: stock
          MYSQL_ROOT_PASSWORD: stock
      volumes:
          - StockDB:/var/lib/mysql
      networks:
          - db_network

  phpmyadmin:
      image: phpmyadmin:5.2.1
      links: 
          - database:db
      ports:
          - 8000:80
      depends_on:
        - database
      networks:
        - db_network
     
networks:
  db_network:

volumes:
  StockDB:
    external: true